# Configuration for chart-releaser
owner: eun2ce
git-repo: llmplan
charts-repo-url: https://eun2ce.github.io/llmplan
target-branch: gh-pages
package-path: .cr-release-packages
index-path: .cr-index
release-name-template: "{{ .Name }}-{{ .Version }}"
