# Default values for llmplan
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: eunheejo/llmplan
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: llmplan.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /api/v1/summary/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/v1/summary/health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

# Application specific configuration
config:
  # LMStudio Configuration
  lmstudio:
    baseUrl: "http://lmstudio:1234/v1"
    apiKey: "lm-studio"
    timeout: 30
    maxRetries: 3

  # Summary Configuration
  summary:
    defaultModelName: "qwen/qwen3-4b"
    defaultMaxTokens: 1000
    defaultTemperature: 0.3
    defaultSummaryType: "concise"
    defaultLanguage: "korean"

# Environment variables
env:
  - name: LMSTUDIO_BASE_URL
    value: "http://lmstudio:1234/v1"
  - name: LMSTUDIO_API_KEY
    value: "lm-studio"
  - name: DEBUG
    value: "false"

# External LMStudio service configuration
lmstudio:
  enabled: true
  service:
    name: lmstudio
    port: 1234
  # If you have LMStudio running externally, set the external IP/hostname
  externalName: "" # e.g., "192.168.1.100" or "lmstudio.example.com"
