apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmplan
  namespace: llmplan
  labels:
    app: llmplan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmplan
  template:
    metadata:
      labels:
        app: llmplan
    spec:
      serviceAccountName: llmplan
      securityContext:
        fsGroup: 2000
      containers:
        - name: llmplan
          image: eunheejo/llmplan:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: LMSTUDIO_BASE_URL
              value: "http://lmstudio:1234/v1"
            - name: LMSTUDIO_API_KEY
              value: "lm-studio"
            - name: DEBUG
              value: "false"
          livenessProbe:
            httpGet:
              path: /api/v1/summary/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/summary/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
