name: Release Helm Chart (DEPRECATED - Use release.yml)

on:
  # Disabled - using unified release.yml workflow  
  workflow_dispatch:  # Allow manual triggering

env:
  HELM_REPO_NAME: llmplan-charts
  CHART_PATH: charts/llmplan

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: "3.14.0"

      - name: Lint Helm Chart
        run: |
          helm lint ${{ env.CHART_PATH }}

      - name: Package Helm Chart
        run: |
          helm package ${{ env.CHART_PATH }} --destination ./helm-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          config: .github/cr.yaml
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  publish-to-oci:
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: "3.14.0"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Package and Push Helm Chart to OCI
        run: |
          helm package ${{ env.CHART_PATH }}
          helm push llmplan-*.tgz oci://registry-1.docker.io/eunheejo
